# Generated by Django 6.0.4 on 2026-06-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej.: SW-AyLP-APE-04', max_length=40, verbose_name='Código APE')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(help_text='Ej.: ape-04-clases-objetos-metodos', unique=True, verbose_name='Slug (URL)')),
                ('resumen', models.CharField(blank=True, help_text='Una línea para la tarjeta del listado.', max_length=300, verbose_name='Resumen')),
                ('contenido', models.TextField(help_text='Enunciado completo en formato Markdown.', verbose_name='Contenido (Markdown)')),
                ('repo_url', models.URLField(blank=True, verbose_name='Repo GitHub')),
                ('pdf', models.CharField(blank=True, help_text='Ruta dentro de static/, ej.: guias/ape-04.pdf', max_length=200, verbose_name='PDF oficial')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('publicada', models.BooleanField(default=True, verbose_name='Publicada')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Guía APE',
                'verbose_name_plural': 'Guías APE',
                'ordering': ['orden', 'codigo'],
            },
        ),
    ]
