# Generated by Django 6.0.4 on 2026-06-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guias', '0003_ape04_companion'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia',
            name='checklist',
            field=models.JSONField(blank=True, default=list, help_text='Lista de entregables (textos) marcables.', verbose_name='Checklist de entrega'),
        ),
        migrations.AddField(
            model_name='guia',
            name='pasos',
            field=models.JSONField(blank=True, default=list, help_text='Lista de pasos (textos) que el estudiante puede marcar.', verbose_name='Pasos de desarrollo'),
        ),
        migrations.AddField(
            model_name='guia',
            name='quiz',
            field=models.JSONField(blank=True, default=list, help_text='Lista de preguntas: {pregunta, opciones[], correcta, explicacion}.', verbose_name='Autoevaluación'),
        ),
    ]
