# Generated by Django 6.0.4 on 2026-04-21 05:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('enunciado', models.TextField()),
                ('categoria', models.CharField(choices=[('resuelto', 'Ejercicio Resuelto'), ('interactivo', 'Ejercicio Interactivo')], max_length=20)),
                ('dificultad', models.CharField(choices=[('basico', 'Básico'), ('medio', 'Medio'), ('avanzado', 'Avanzado')], default='basico', max_length=20)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('entrada', models.TextField(blank=True, verbose_name='Entradas (IPO)')),
                ('proceso', models.TextField(blank=True, verbose_name='Proceso (IPO)')),
                ('salida', models.TextField(blank=True, verbose_name='Salidas (IPO)')),
                ('pseudocodigo', models.TextField(blank=True, verbose_name='Pseudocódigo')),
                ('codigo_cpp', models.TextField(help_text='Código C++17 que el estudiante leerá. NO se ejecuta en el servidor.', verbose_name='Código C++ educativo')),
                ('solucion_esperada', models.TextField(help_text='Valor correcto. Python lo compara con la respuesta del estudiante.', verbose_name='Respuesta esperada')),
                ('tipo_respuesta', models.CharField(choices=[('entero', 'Número entero'), ('decimal', 'Número decimal'), ('texto', 'Texto')], default='entero', help_text='Tipo de dato de la respuesta esperada (para validación inteligente).', max_length=10)),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
                'ordering': ['tema__unidad', 'tema__orden', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tema', models.CharField(max_length=100)),
                ('descripcion', models.TextField(verbose_name='Teoría resumida')),
                ('unidad', models.IntegerField(choices=[(1, 'U1: Lógica, Algoritmos y Pseudocódigo'), (2, 'U2: Variables, Operadores y Estructuras de Control'), (3, 'U3: Programación Orientada a Objetos'), (4, 'U4: Estructuras de Datos')])),
                ('orden', models.IntegerField(default=0, help_text='Posición dentro de la unidad')),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'ordering': ['unidad', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('estudiante', 'Estudiante'), ('admin', 'Administrador')], default='estudiante', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Intento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_usuario', models.TextField()),
                ('resultado', models.CharField(choices=[('correcto', 'Correcto'), ('incorrecto', 'Incorrecto')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='ejercicios.ejercicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intento',
                'verbose_name_plural': 'Intentos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Retroalimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_correcto', models.TextField()),
                ('mensaje_error', models.TextField()),
                ('recomendacion', models.TextField(blank=True, help_text='Tema o ejercicio recomendado para repasar.')),
                ('ejercicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retroalimentacion', to='ejercicios.ejercicio')),
            ],
            options={
                'verbose_name': 'Retroalimentación',
                'verbose_name_plural': 'Retroalimentaciones',
            },
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='ejercicios.tema'),
        ),
    ]
