# Generated by Django 6.0.4 on 2026-04-21 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.IntegerField()),
                ('total', models.IntegerField(default=0)),
                ('correctos', models.IntegerField(default=0)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progreso_unidades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso por unidad',
                'verbose_name_plural': 'Progresos por unidad',
                'ordering': ['unidad'],
                'unique_together': {('usuario', 'unidad')},
            },
        ),
    ]
