# Generated by Django 6.0.4 on 2026-05-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0003_add_lenguaje_to_ejercicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='codigo_cpp',
            field=models.TextField(help_text='Código que el estudiante leerá. NO se ejecuta en el servidor.', verbose_name='Código educativo (C++ o Python)'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='lenguaje',
            field=models.CharField(choices=[('cpp', 'C++'), ('python', 'Python'), ('java', 'Java')], default='cpp', max_length=10, verbose_name='Lenguaje del código'),
        ),
    ]
