# Generated by Django 6.0.4 on 2026-06-02 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0004_alter_ejercicio_codigo_cpp_alter_ejercicio_lenguaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=1, help_text='Orden de revelación (1, 2, 3...)')),
                ('texto', models.TextField(verbose_name='Texto de la pista')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pistas', to='ejercicios.ejercicio')),
            ],
            options={
                'verbose_name': 'Pista',
                'verbose_name_plural': 'Pistas',
                'ordering': ['ejercicio', 'orden'],
            },
        ),
    ]
