# Generated by Django 6.0.4 on 2026-06-03 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0005_pista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('unidad', 'Unidad completada'), ('primer_paso', 'Primer paso'), ('volumen', 'Volumen')], max_length=20)),
                ('clave', models.CharField(help_text='Identificador único del logro por usuario.', max_length=50)),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('icono', models.CharField(default='🔔', max_length=8)),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha'],
                'unique_together': {('usuario', 'clave')},
            },
        ),
    ]
