# Generated by Django 6.0.4 on 2026-06-03 08:49

from django.db import migrations, models


# Mapa de los emojis (v1 del modelo) a los nombres de ícono SVG (v2).
EMOJI_A_NOMBRE = {
    '🔔': 'bell',
    '🌱': 'sprout',
    '🏆': 'trophy',
    '📈': 'trending-up',
}
NOMBRE_A_EMOJI = {nombre: emoji for emoji, nombre in EMOJI_A_NOMBRE.items()}


def emojis_a_nombres(apps, schema_editor):
    """Convierte los emojis ya guardados en notificaciones a nombres de ícono."""
    Notificacion = apps.get_model('ejercicios', 'Notificacion')
    for emoji, nombre in EMOJI_A_NOMBRE.items():
        Notificacion.objects.filter(icono=emoji).update(icono=nombre)


def nombres_a_emojis(apps, schema_editor):
    """Reverso: vuelve a los emojis (por si se revierte la migración)."""
    Notificacion = apps.get_model('ejercicios', 'Notificacion')
    for nombre, emoji in NOMBRE_A_EMOJI.items():
        Notificacion.objects.filter(icono=nombre).update(icono=emoji)


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0006_notificacion'),
    ]

    operations = [
        # 1) Ampliar el campo y cambiar el default ANTES de migrar datos
        #    (para que 'trending-up' (11 chars) entre en el nuevo max_length=20).
        migrations.AlterField(
            model_name='notificacion',
            name='icono',
            field=models.CharField(default='bell', help_text='Nombre del ícono SVG (templates/icons/<nombre>.svg).', max_length=20),
        ),
        # 2) Migrar los datos existentes: emoji -> nombre.
        migrations.RunPython(emojis_a_nombres, nombres_a_emojis),
    ]
